on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag not containing /
  workflow_dispatch:

name: Cloud Deploy Workflow

permissions: write-all

jobs:
  deploy:
    name: Deploy To Oxyde Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: {{ toolchain }}
          profile: minimal
          override: true
          components: rustfmt, clippy, rust-src

      - name: Cache
        uses: Swatinem/rust-cache@v2

#       - name: Check formatting
#         run: cargo fmt --check
#       - name: Clippy
#         run: cargo clippy --features docs,math --tests -- -D warnings
#       - name: Run tests
#         run: cargo test

      - name: Deploy to Oxyde Cloud
        uses: Synphonyte/oxyde-cloud-deploy-action@v1
        with:
          {% raw %}api-token: ${{ secrets.OXYDE_CLOUD_TOKEN }}{% endraw %}
          cloud-config-file: oxyde-cloud.toml

